### ISSUE TITLE
Thank you! Please share an option for donation

### ISSUE THREAD

**Issue by s0nerik** [dumazy/kerekewere#2]
Thank you, mate! This is the most important set of lints I have in some of my projects now.

This library enforces exactly the import rules I wanted to be enforced by the built-in linter out-of-the-box ever since I started using Dart.

Now I can finally ditch the cumbersome monorepo structure for some of my projects and simply rely on the linter for enforcing the import rules I consider sane for a single-package application.

Writing this to let you know that your work is appreciated and to give you some motivation for continuing to support this lib.

I'd love to buy you a coffee/beer/cola/whatever, so please let me (and others) know how I can donate to you.

**Comment by dumazy** [comment]
Hi Alex,

Very happy to hear that this little package was able to help you out! It
was just a small thing to use internally but I want to expand on it.

The plan is to clearly document the way of using smaller "subpackages"
(still looking for a good name for this) and have this package as a tool
for it.

Thanks for offering a small donation, but feedback is worth a lot already
🙏🙏

Just curious, how did you find this? I don't think I shared anything about
it yet.

Best regards,
Fré

**Comment by s0nerik** [comment]
> The plan is to clearly document the way of using smaller "subpackages"
(still looking for a good name for this) and have this package as a tool
for it.

IIRC, older Dart documentation actually recommended using "lightweight packages" approach as a best practice somewhere, but never actually explained what the "lightweight package" is. Anyway, I think that "subpackage" is a good term for this.

> Just curious, how did you find this? I don't think I shared anything about
it yet.

Having the intuition that I'm not alone who wants some guaranteed degree of encapsulation for various parts of the app, and knowing that `custom_lint` exists, I decided to search pub for all packages that use it once again and found this weirdly named one. :)

**Comment by dumazy** [comment]
Alright, that's nice to hear.

Since this is now used by others outside of our internal team, I went ahead and made some changes:
- Renamed to "subpackage_lint"
- Marked "kerekewere" as discontinued
- Added a "Philosophy" section to the README to explain the usage of subpackages
- Added the donation button you requested 😅 
- Bumped the version to 1.0.0. No reason to be "afraid" of going stable

I'd love to hear more feedback, so feel free to create issues here if something pops up!
